---
AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Deploys a route table for the VCP and Internet Gatway, Nat Gatways for Internet.

#-------------------------------------------------------------------------------------------------#
# Parameters                                                                                      #
#-------------------------------------------------------------------------------------------------#
#Parameters:


#-------------------------------------------------------------------------------------------------#
# Resources                                                                                       #
#-------------------------------------------------------------------------------------------------#
Resources:
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: nonprod-navist-vpc-internetgateway
        - Key: VpcId
          Value: !ImportValue nonprod-navist-vpc::Vpc

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !ImportValue nonprod-navist-vpc::Vpc

  # NatGatewayA:
  #   Type: AWS::EC2::NatGateway
  #   Properties:
  #     AllocationId: !GetAtt EipA.AllocationId
  #     SubnetId: !ImportValue nonprod-navist-vpc::PublicSubnetA
  # EipA:
  #   Type: AWS::EC2::EIP
  #   DependsOn: InternetGatewayAttachment
  #   Properties:
  #     Domain: vpc
  # DefaultPrivateRouteA:
  #   Type: AWS::EC2::Route
  #   Properties:
  #     RouteTableId: !Ref PrivateRouteTable
  #     DestinationCidrBlock: 0.0.0.0/0
  #     NatGatewayId: !Ref NatGatewayA

  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !ImportValue nonprod-navist-vpc::Vpc
      Tags:
        - Key: Name
          Value: nonprod-navist-vpc-routetable-public

  PublicSubnetAAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !ImportValue nonprod-navist-vpc::PublicSubnetA

  PublicSubnetBAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !ImportValue nonprod-navist-vpc::PublicSubnetB

  PublicSubnetCAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !ImportValue nonprod-navist-vpc::PublicSubnetC

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !ImportValue nonprod-navist-vpc::Vpc
      Tags:
        - Key: Name
          Value: nonprod-navist-vpc-routetable-private

  PrivateSubnetAAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !ImportValue nonprod-navist-vpc::PrivateSubnetA

  PrivateSubnetBAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !ImportValue nonprod-navist-vpc::PrivateSubnetB

  PrivateSubnetCAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !ImportValue nonprod-navist-vpc::PrivateSubnetC

  SecureRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !ImportValue nonprod-navist-vpc::Vpc
      Tags:
        - Key: Name
          Value: nonprod-navist-vpc-routetable-secure

  SecureSubnetAAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref SecureRouteTable
      SubnetId: !ImportValue nonprod-navist-vpc::SecureSubnetA

  SecureSubnetBAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref SecureRouteTable
      SubnetId: !ImportValue nonprod-navist-vpc::SecureSubnetB

  SecureSubnetCAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref SecureRouteTable
      SubnetId: !ImportValue nonprod-navist-vpc::SecureSubnetC
